config/routes.rb
Beatbucks::Application.routes.draw do
  
     
    resources :payment_notifications

    resources :line_items

  resources :carts do
    member do
      get :checkout
      get :billing
      post :save_billing
      get :download
    end
    collection do
      get :current
      get :billing_payments
      get :billing_payments2
      get :billing_payments3
      post :complete_payment
      get :payment_done
      get :license_agrement
      post :add_to_cart
      
      get :latest_pending_cart
      get :latest_pending_line_items
    end
    end

   resources :glacier_details

   devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", :registrations => "registrations" }
  as :user do
    get "settings" => "users#settings"
    get "social_networks" => "users#social_networks"
    put "users/:id/save_settings" => "users#save_settings"
    get "/profile" => "registrations#edit"
  end
  #map.current_cart 'cart', :controller => 'carts', :action => 'show', :id => 'current'
   get "/users/index"
   get "/registrations/update"
   post "/registrations/update"
   get "/home/state_cities"
   get "/home/state_codes"
   get "/dashbord" => "home#dashbord"
   get "/edit" => "users#edit"
   post "/tracks/download_zip" => "tracks#download_zip"
   post "/home/settings"
   get "/home/sub_genres"
   get "/beatpacks" => "beatpacks#new"
   get "/earnings" => "producers#earnings"

    get "/buy" => "users#buy"
    get "/license" => "users#license"
    get "/music" => "users#music"
    get "/files" => "users#files"
  get "/descripition" => "users#descripition"
  get "/author_profile/:id" => "users#author_profile"
  
  get "/orders" => "users#orders"
  get "/about_us" => "home#about_us"
  get "global_search" => "users#global_search"
  put "set_song_in_session" => "users#set_song_in_session"

    resources :tracks do
      member do
        get :download
        post :upload_tpt_file
        post :publish
        get :new_track_step2
        get :mp3_download
        get :download_zip
        get :download_wav
        get :download_tpt
        get :increment_play_count
      end
    
    collection do
      post :upload_trak_file
      get :upload_trak_file
      get :license
      get :new1
    end
    end
    resources :beatpacks 
  
  
  root 'users#index'  
  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items
  has_one :billing_detail
  attr_accessible  :purchased_at
  accepts_nested_attributes_for :line_items

  scope :belongs_to_user, lambda{|user| where(:id => BillingDetail.select(:cart_id).where(:user_id => user.id))}
  scope :completed, lambda{ where(:status => "completed")}

  def total_price
    line_items.to_a.sum(&:full_price)
  end
  
  def paypal_url(return_url, notify_url)
    order_id = Time.now.to_i
    values = {
      :business => AppConfig.paypal_email,
      :cmd => '_cart',
      :upload => 1,
      :return => return_url,
      :invoice => order_id,
      :notify_url => notify_url
    }
    
    line_items.each_with_index do |item, index|
      values.merge!({
        "amount_#{index+1}" => item.unit_price,
        "item_name_#{index+1}" => item.track.title,
        "item_number_#{index+1}" => item.id,
        "quantity_#{index+1}" => item.quantity
      })
    end
    self.order_id = order_id
    self.save
    ret_url = AppConfig.paypal_url + values.to_query
    return ret_url
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  #before_filter :get_layout

  def current
    @cart = current_cart
    if current_cart.line_items.empty?
      flash[:notice] = "Your Cart is empty to checkout"
      redirect_to root_path
    end
  end
  
  def license_agrement
    @cart = current_cart
    @track_id = params[:product_id]
    @track_type = params[:track_type]
    @product = Track.find(params[:product_id])
    @unit_price = 0
    if params[:track_type] == "promotion"
    	@unit_price = @product.promotion_licence_price
      if @product.present? && @product.promotion_tpt_price.present?
        @unit_tpt_price = @product.promotion_tpt_price
      end
    elsif params[:track_type] == "profit"
    	@unit_price = @product.profit_licence_price
      if @product.present? && @product.profit_tpt_price.present?
        @unit_tpt_price = @product.profit_tpt_price
      end
   	elsif params[:track_type] == "exclusive"
   		@unit_price = @product.exclusive_licence_price
      if @product.present? && @product.exclusive_tpt_price.present?
        @unit_tpt_price = @product.exclusive_tpt_price
      end
    end
    
  end
  
  def billing_payments
    @cart = current_cart
    if current_cart.line_items.empty?
      flash[:notice] = "Your Cart is empty to checkout"
      redirect_to root_path
    end
  end
  
  def billing_payments2
    if current_cart.line_items.empty?
      flash[:notice] = "Your Cart is empty to checkout"
      redirect_to root_path
    end
    @billing_detail = BillingDetail.new
    if current_user.present?
      @billing_detail.first_name = current_user.Firstname
      @billing_detail.last_name = current_user.Lastname
      @billing_detail.email = current_user.email
      @billing_detail.country = current_user.Country
      # @billing_detail.user_id = 1
    end
    @cart = current_cart
  end
  
  def complete_payment
   @billing_detail = BillingDetail.new(params[:billing_detail])
    # @billing_detail.user_id = 1
    @billing_detail.cart_id = current_cart.id
    if @billing_detail.invalid?
      flash[:notice] = "Please Fill All Details Below"
      redirect_to billing_payments2_carts_path
    
  else
    @billing_detail.save!
  
    @cart = current_cart
    pay_pal_url = @cart.paypal_url(payment_done_carts_url(cart_id: @cart.id), payment_notifications_url)
    redirect_to pay_pal_url
  end
  end
  
  def payment_done
    @cart = Cart.find(params[:cart_id]) 
    @cart.status = 'completed'
    @cart.save
    render "download"
  end

  def billing
    @cart = Cart.find(params[:id])
    @line_items = @cart.line_items
    @total_value = @line_items.inject(0){|sum, li| sum+li.unit_price}
    @billing_details = BillingDetail.new
    if current_user.present?
      @billing_details.user_id = current_user.id
      @billing_details.first_name = current_user.Firstname
      @billing_details.last_name = current_user.Lastname
      @billing_details.email = current_user.email
      @billing_details.cart_id = @cart.id
    end
  end

  def save_billing
    @billing_detail = BillingDetail.new(billing_detail_params)
    if @billing_detail.save
      redirect_to download_cart_path(@billing_detail.cart)
    else
      render "billing"
    end
  end
  
  def download
    @cart = Cart.find(params[:id])
  end
  
  def checkout
    @cart = Cart.find(params[:id])
    @line_items = @cart.line_items
    @total_value = @line_items.inject(0){|sum, li| sum+li.unit_price}
  end
  
  def add_to_cart
    if params[:cart_id].present?
      session[:cart_id] = params[:cart_id] 
    end
    @cart = current_cart
    if params[:selectedTracks].present?
      unless @cart.present?
        @cart = Cart.new do |cart|
          cart.purchased_at = Date.today
          cart.status = 'pending'
        end
      end
      ActiveRecord::Base.transaction do
        @toal_value = 0
        if @cart.save
          @line_items = params[:selectedTracks].map do |key, val|
            LineItem.new({:track_id => val[:track_id], :item_type => val[:item_type], :tpt_flag => val[:tpt_flag]}) do |li|
              li.cart_id = @cart.id
              if li.tpt_flag
                li.unit_price = val[:licencePrice].to_i + val[:tptLicencePrice].to_i
              else
                li.unit_price = val[:licencePrice].to_i
              end
              
            end
          end
          if(@line_items.map(&:save).all?)
            render :js => "window.location = '#{checkout_cart_path(@cart)}'"
          end
        else
          raise ActiveRecord::Rollback
        end
      end
    elsif @cart.line_items.count > 0
      render :js => "window.location = '#{checkout_cart_path(@cart)}'"
    else
      render :js => "window.location = '#{root_path}'"
    end
  end
  
  def latest_pending_cart
    respond_to do |format|
      format.json do
        pending_cart = current_user.present? ? Cart.belongs_to_user(current_user).where(:status => "pending").last : nil
        if pending_cart.present?
          pending_items = pending_cart.line_items.count
          pending_total = pending_cart.line_items.inject(0){|sum, item| sum+item.unit_price}
          render :json => {:cart_id => pending_cart.id, :pending_items => pending_items, :pending_total => pending_total}
        else
          render :json => {:cart_id => nil}
        end
      end
    end
  end

  def latest_pending_line_items
    respond_to do |format|
      format.json do
        pending_cart = current_user.present? ? Cart.belongs_to_user(current_user).where(:status => "pending").last : nil
        if pending_cart.present?
          pending_items = pending_cart.line_items.map{|li| {:id => li.id, :title => li.track.title, :unit_price => li.unit_price} }
          render :json => {:line_items => pending_items}
        else
          render :json => {:line_items => []}
        end
      end
    end

  end
  

  private

  def billing_detail_params
    params.require(:billing_detail).permit(:first_name, :last_name, :artist_name, :email, :cart_id, :user_id)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_billing_payments.html.erb
<div id="page-wrapper">
  <div class="container-fluid no-space">

    <!-- Page Heading -->
    <div class="row no-space">
      <div class="col-lg-12 no-space vert-text">
        <div class="container-fluid">
          <div class="col-md-1"></div>
            <div class="col-md-10">
              <div class="row selectboxtspace">
                <%= image_tag('billinginfo2.png', :class=>"img-responsive") %>
              </div>
              <div class="row selectboxtspace">
                  
                 <div class="row no-space">
                    <div class="container-fluid">
                       <div class="col-md-8 col-lg-8 billinginfoborder">
                        <div class="col-md-6 billinfoborderleft">
                          <div class="row">
                            <p class="loginTextyouraccount text-left">
                              Log in to your account
                            </p>
                          </div>
                          <%= form_for(User.new, :url => session_path(User.new)) do |f| %>
                            <div class="form-group">
                              <div class="settingsubTitle text-left">  
                                <%= f.label :Email %>
                              </div>
                              <div class="col-sm-12 no-space">
                                <%= f.email_field :email, :class=>"form-control", :autofocus => true  %>
                              </div>
                            </div>
                            <div class="form-group">
                              <div class="settingsubTitle text-left"><%= f.label :Password %></div>
                              <div class="col-sm-12 no-space">
                                <%= f.password_field :password, :class=>"form-control" %>
                              </div>
                              <div class="col-sm-8 forgotpass text-left no-space"><a href="#">Forgot your password?</a></div>
                            </div>
                            <div class="form-group">
                              <div class="col-sm-7 pull-left text-left no-space">
                                <button type="submit" class="btn btn-default signin">Log in</button>
                              </div>
                            </div>
                          <% end %>
                        </div>
                        
                        <div class="col-md-6">
                          <div class="row billinginfoborder2">
                            <p class="continewwithoutlogin">Continue without logging in</p>
                            <p class="billintext">You'll have the option to register for an account after your purchase</p>
                          </div>
                          <p>
                            <button class="btn btn-info btnbg billintextbtn"><%= link_to 'Continue as a guest', billing_payments2_carts_path ,  :style=>"color: #FFFFFF" %><i class=" fa fa-play"></i> 
                            </button>
                          </p>
                         </div>
                        </div>
                        <div class="col-md-3 boxborder billingmleft">
                          <h5 class="ordardetails mspace2 mtop text-left col-xs-offset-1">Order Details</h5>
                          <% @cart.line_items.each_with_index do |li, a| %>
                          <div class="row mspace3">
                            <div class="col-md-6 settingsubTitle text-left"><%= li.track.title %></div>
                              <div class="col-md-6 settingsubTitle text-right">$<%= li.unit_price %></strong></div>
                          </div>
                          <% end %>
                          <hr/>
                          <div class="row mspace3">
                            <div class="col-md-6 settingsubTitle"><strong>TOTAL</strong></div>
                            <div class="col-md-6"><strong>$<%= @cart.total_price%></strong></div>
                          </div>
                        </div> 
                      </div>
                    </div> 
                  </div>
              </div>
            </div>
          </div>
        </div><!-- /.row -->
      </div><!-- /#page-wrapper -->
    

app/views/carts/_review.html.erb
  <div id="page-wrapper">
  <div class="container-fluid no-space">
  <!-- Page Heading -->
    <div class="row no-space">
      <div class="col-lg-12 no-space vert-text">
        <div class="container-fluid">
          <div class="col-md-10">
            <div class="row selectboxtspace">
              <div class="col-md-9"><%= image_tag('billinginfo1.png', :class=>"img-responsive") %></div>
               <div class="col-md-2 keepshopping text-right">
                <a href="<%= root_path %>"><%= image_tag('arrowleft2.png') %> &nbsp; KEEP SHOPPING</a>
              </div>
            </div>    
                  
            <div class="row selectboxtspace">
              <div class="row no-space">
                <div class="container-fluid">
                   <div class="col-md-12 col-lg-12">
                    <div class="row billpayment1bg">
                        <div class="col-md-3 col-lg-3 col-xs-3 billpayment1title">
                          Track 
                        </div>
                        <div class="col-md-2 col-lg-2 col-xs-3 billpayment1title">
                          Format
                        </div>
                        <div class="col-md-3 col-lg-3 col-xs-2 billpayment1title">
                          License
                        </div>
                        <div class="col-md-2 col-lg-2 col-xs-2 billpayment1title">
                          Optins
                        </div>
                        <div class="col-md-2 col-lg-2 col-xs-1 billpayment1title">
                          Total
                        </div> 
                      </div>
                                
                      <% @cart.line_items.each_with_index do |li, a| %>
                      <div class="row billpayment1bg2">
                        <div class="col-md-3 col-lg-3 col-xs-3 billpayment1title">
                          <div class="row">
                              <div class="col-md-5 no-space">
                               <div id="play-bg" style="background-image:url(<%= li.track.track_image.url(:thumb) %>); "  >
                                 <%= render 'tracks/track_player', :track => li.track, id: "player" %>
                               </div>

                              
                                  <%#= image_tag 'play.png' %>
                                  <%#= render 'tracks/track_player', :track => li.track %>
                               </div>
                                <div class="col-md-7 no-space">
                                  <div class="billpaysubtitieldevel"><%= li.track.title %></div>
                                    <div class="billpaysubtitielid"><%= li.track.subgenere %></div>
                                    <div class="billpaysubtfromid">From: MR. 
                                      <%= li.track.user ? li.track.user.Firstname.upcase : "stephan".upcase %>

                                      <%#= li.track.user.Firstname %></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2 col-lg-2 col-xs-3 billpayment1title">
                          <select class="selectrecet">
                              <option value="wav">wav</option>
                          </select>
                          <div class="billnoncomsub">$0.00</div>
                        </div>
                        <div class="col-md-3 col-lg-3 col-xs-2 billpayment1title">
                          <div class="billnoncom">Non-commercial</div>
                          <div class="billnoncomsub2">$<%= li.unit_price %></div>
                        </div>
                        <div class="col-md-2 col-lg-2 col-xs-2 billpayment1title">
                          <div class="billnoncom">TPT</div>
                          <div class="billnoncomsub2">$<%= @unit_tpt_price %></div>
                        </div>
                        <div class="col-md-2 col-lg-2 col-xs-1 billpayment1title">
                          <div class="billtotal">$<%= li.unit_price %></div>
                            <div class="billedit">
                              <ul>
                                <li><a href="#">Edit</a><%#= link_to "Edit", edit_cart_path(@cart) %></li>
                                <li><%= link_to 'Remove', li, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                              </ul> 
                            </div>
                        </div>
                      </div>
                      <% end %>
                      <div class="row">
                        <div class="col-md-3 col-lg-3 col-xs-3 billpayment1title">
                          <div class="row billpayment1bg2 totaldownloadgb">
                              <div class="col-md-12 no-space billpaysubtitielid">
                                  Total download size : <%#= li.track.tpt_file_size %>
                                </div>
                                
                            </div>
                        </div>
                        <div class="col-md-2 col-lg-2 col-xs-1 billpayment1title">
                          <a href="<%= current_user.present? ? billing_payments2_carts_path : billing_payments_carts_path %>"><%= image_tag('checkout.png') %></a>
                        </div> 
                        
                      </div>              
                  </div>            
                </div>
              </div>           
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<style type="text/css">


  
  #play-bg{
    margin: -10px;
  }
</style>

app/views/carts/billing_payments2.html.erb
<%= render "shared/top_bar"%>
<!-- hero unit -->
<!-- /.hero unit -->
<div id="jquery_jplayer_1" class="jp-jplayer"></div>
<div id="jp_container_N" class="jp-video jp-video-270p">
  <div class="jp-type-playlist">
    <%= render "shared/music_player"%>
    <!-- music player -->
    <!-- /.music player -->
    <!-- playlist model -->
  </div>
</div>

<div class="container">
</div>
<%= render "billing_payments2" %>
<%= render "shared/footer"%>
<%= render "shared/mini_footer"%>

app/views/carts/current.html.erb
<h3><%= notice %></h3>
<%= render "review" %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/license_agrement.html.erb
<%= javascript_include_tag 'jquery' %>
<% if @track_type == 'profit' %>
  <%= render "profit", :product => @product %>
<% end %>
<% if @track_type == 'exclusive' %>
  <%= render "exclusive", :product => @product %>
<% end %>
<% if @track_type == 'promotion' %>
  <%= render "promotion", :product => @product %>
<% end %>

  <div class="col-md-4 col-lg-4 navtopfix">
    <div class="row navtopbg">
      <div class="col-lg-3">
        <%= image_tag @product.track_image.url, :size => '90x90' %>
      </div>
      <div class="col-lg-6">
        <div class="licencedeveltext"><%= @product.title %></div>
          <div class="licencemrbig">
            <span class="licenceby">by</span> <%= current_user ? current_user.Firstname.upcase : "Guest" %>
          </div>
        <div class="licenceeastcost">
          <%= @product.subgenere %>
        </div>
        <div class="licencedate"><%= @product.created_at.strftime "%Y/%m/%d" %></div>  
      </div>
      <div class="col-lg-3 licencelikesspacetop">
        <div class="licencelikes"><%= image_tag('u703_normal.png') %></div>
          <div class="licencelikes"><%= image_tag('u701_normal.png') %></div>
          <div style="color:#ffffff; font-size:15px;">!</div>
      </div>
      <div class="row">
        <div class="col-lg-11 col-md-11" style="margin-left:20px;">
          <div class="demo">
            <div id="horizontalTab">
              <ul class="resp-tabs-list">
                <li>Licenses</li>
                <li><%= link_to "Music", music_path, :method => :get, :remote =>true, :style =>"color: #FFFFFF" %></li>
                <li><%= link_to "Files", files_path, :method => :get, :remote =>true, :style =>"color: #FFFFFF" %></li>
                <li><%= link_to "Description", descripition_path, :method => :get, :remote =>true, :style =>"color: #FFFFFF" %></li>
              </ul>

              <div class="resp-tabs-container">
                <div>
                  <div class="row">
                    <div id = "remove_selected">
                      <div class="col-md-6">
                        <span class="field-tip">
                          <p class="tooltipTitle">
                            <% if @track_type == 'profit' %>Profit Only<% end %>
                            <% if @track_type == 'exclusive' %>Exclusive Only<% end %>
                            <% if @track_type == 'promotion' %>Promotion Only<% end %></p>
                        <span class="tip-content">
                          <div class="toolheadline">license for one (1) non-profit use only.</div>
                          <div class="row">
                            <div class="col-md-2 col-lg-2 toolheadsubtext">Do's:</div>
                            <div class="col-md-10 col-lg-10">
                              <ul class="toolheadsubtext">
                                <li>Alter</li>
                                  <li>Record a song</li>
                                  <li>Make a music video*</li>
                                  <li>Perform at events</li>
                                  <li>GIVE copies</li>
                              </ul>
                            </div>
                          </div>   
                          <div class="row">
                            <div class="col-md-2 col-lg-2 toolheadsubtext">Dont's</div>
                            <div class="col-md-10 col-lg-10">
                              <ul class="toolheadsubtext">
                                <li>SELL copies </li>
                                <li>USE in advertizing</li>
                                <li>Associate to brand</li>
                              </ul>
                            </div>
                          </div>
                          <div class="toolheadline tracksearchmspace">*Video can't be monetizing on YouTube</div>
                        </span>
                      </span>   
                    </div>

                    <div class="col-md-6 no-space">
                      <p class="remove_btn removebtn text-right"><a style="cursor:pointer"> Remove</a></p>
                    </div>
                    <div class="col2-DIV">
                      <div class="row licencemargin">
                        <div class="col-md-6 col-lg-6 text-left">
                          <div class="license">
                            <%= image_tag('rightarrow.png', :class=>"liscensespace") %>License</div>
                        </div>
                          <div class="col-md-6 col-lg-6 licencerate text-right">
                            $<%= @unit_price %> <span class="licencedeg">00</span>
                          </div>
                        </div>                
                      <input type="hidden" id="tpt_price" value="<%= @unit_tpt_price %>" >
                      <input type="hidden" id="unit_price" value="<%= @unit_price %>" >
                        <% if @unit_tpt_price.present? %>
                        <div class="lic-div">
                          <div class="col-md-6 col-lg-6 text-left">
                            <p class="license">
                            <input type="checkbox" id="tpt_check_box"  />
                            TPT License<span style="margin-bottom:20px;">
                            <%= image_tag('u656_normal.png') %></span></p>
                        </div>
                        <div class="col-md-6 col-lg-6 licencerate text-right">
                            +&nbsp; &nbsp;$<%= @unit_tpt_price %> <span class="licencedeg">00</span>
                          </div>
                      </div>  
                      <% end %>
                    </div>
                    <div class="hrspace2">   </div>

                    <div class="row hr-space">
                      <div class="col-md-6 col-lg-6 licenceTotal">
                        TOTAL
                      </div>
                        
                      <div class="col-md-6 col-lg-6 licenceTotaldollors text-right">
                        <span style="font-size:14px !important; padding-bottom:-20px;" >$</span><span class="fif" id="total_amount_div"><%= @unit_price %></span><span style="font-size:14px !important; padding-bottom:-20px;">.00</span>
                      </div>
                    </div>

                    <input type="checkbox" id="agree_checkbox"> 
                      <div class="agreement" style="color:#FFF">By clicking ''I AGREE'', you accept the terms and conditions of this </div> 
                      <div class="agree_btn_div">
                        <%= link_to image_tag('u1334_normal.png'), line_items_path(:product_id => @product, :track_type => @track_type, :tpt_flag => true), :method => :post, :class => 'submit_btn1 submit_btn' %>
                        <%= link_to image_tag('u1334_normal.png'), line_items_path(:product_id => @product, :track_type => @track_type, :tpt_flag => false), :method => :post, :class => 'submit_btn2 submit_btn' %>
                      </div>
                    </div>

                <div id = "select_again" style="color:#FFF">
                  <% if @product.promotion_licence_price %>
                  <h3 title="<%= promotion_dos_dont_text %>" data-placement="bottom"  data-html="true" rel="tooltip">Promotion only</h3>
                    <ul class="select">
                      <li><%= link_to "Select", license_agrement_carts_path(:product_id => @product, :track_type => "promotion") %></li>
                        <li>$<%= @product.promotion_licence_price %></li>
                    </ul>
                  <% end %>
                  <% if @product.profit_licence_price %>
                  <h3 title="<%= profit_dos_dont_text %>" data-placement="bottom"  data-html="true" rel="tooltip">For Profit</h3>
                  <ul class="select">
                    <li><%= link_to "Select", license_agrement_carts_path(:product_id => @product, :track_type => "profit") %></li>
                    <li>$<%= @product.profit_licence_price %></li>
                  </ul>
                  <% end %>
                  <% if @product.exclusive_licence_price %>
                  <h3 title="<%= exclusive_dos_dont_text %>" data-placement="bottom"  data-html="true" rel="tooltip">Exclusive</h3>
                  <ul class="select">
                    <li><%= link_to "Select", license_agrement_carts_path(:product_id => @product, :track_type => "exclusive") %></li>
                      <li>$<%= @product.exclusive_licence_price %></li>
                  </ul>
                  <% end %>
                </div>
             </div>

<script>
$(document).ready(function() {
  $("#select_again").hide();
  $('.submit_btn1').hide();
  $('.submit_btn2').hide();
  $(".checkout_click").click(function(){
    $(location).attr('href',"<%= current_user.present? ? billing_payments2_carts_path : billing_payments_carts_path %>");
  });
  $(".remove_btn").click(function(){
    $("#select_again").show();
    $("#remove_selected").hide();
  });
  $("#agree_checkbox").click(function(){
    var checked = $(this).attr('checked');
    if(this.checked){
      if($("#tpt_check_box").attr('checked')){
        $('.submit_btn1').show();
        $('.submit_btn2').hide();
      }else{
        $('.submit_btn1').hide();
        $('.submit_btn2').show();
      }
    }else{
      $('.submit_btn').hide();
    }
  });
  $("#tpt_check_box").click(function(){
    tot_price = $("#unit_price").val();
    if($(this).is(':checked')){
      tot_price = parseFloat(tot_price) + parseFloat($("#tpt_price").val());
      $('.submit_btn1').show();
      $('.submit_btn2').hide();
    }else{
      $('.submit_btn1').hide();
      $('.submit_btn2').show();
    }
    if(!$("#agree_checkbox").attr('checked')){
      $('.submit_btn').hide();
    }
    $("#total_amount_div").html(tot_price)
  });
});
</script>
<%= javascript_include_tag 'easyResponsiveTabs.js' %>
<script type="text/javascript">
    $(document).ready(function () {
        $('#horizontalTab').easyResponsiveTabs({
            type: 'default', //Types: default, vertical, accordion           
            width: 'auto', //auto or any width like 600px
            fit: true,   // 100% fit in a container
            closed: 'accordion', // Start closed if in accordion view
            activate: function(event) { // Callback function if tab is switched
                var $tab = $(this);
                var $info = $('#tabInfo');
                var $name = $('span', $info);
                $name.text($tab.text());
                $info.show();
            }
        });

        $('#verticalTab').easyResponsiveTabs({
            type: 'vertical',
            width: 'auto',
            fit: true
        });
    });
</script>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>