config/routes.rb
Beatbucks::Application.routes.draw do
  
     
    resources :payment_notifications

    resources :line_items

  resources :carts do
    member do
      get :checkout
      get :billing
      post :save_billing
      get :download
    end
    collection do
      get :current
      get :billing_payments
      get :billing_payments2
      get :billing_payments3
      post :complete_payment
      get :payment_done
      get :license_agrement
      post :add_to_cart
      
      get :latest_pending_cart
      get :latest_pending_line_items
    end
    end

   resources :glacier_details

   devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", :registrations => "registrations" }
  as :user do
    get "settings" => "users#settings"
    get "social_networks" => "users#social_networks"
    put "users/:id/save_settings" => "users#save_settings"
    get "/profile" => "registrations#edit"
  end
  #map.current_cart 'cart', :controller => 'carts', :action => 'show', :id => 'current'
   get "/users/index"
   get "/registrations/update"
   post "/registrations/update"
   get "/home/state_cities"
   get "/home/state_codes"
   get "/dashbord" => "home#dashbord"
   get "/edit" => "users#edit"
   post "/tracks/download_zip" => "tracks#download_zip"
   post "/home/settings"
   get "/home/sub_genres"
   get "/beatpacks" => "beatpacks#new"
   get "/earnings" => "producers#earnings"

    get "/buy" => "users#buy"
    get "/license" => "users#license"
    get "/music" => "users#music"
    get "/files" => "users#files"
  get "/descripition" => "users#descripition"
  get "/author_profile/:id" => "users#author_profile"
  
  get "/orders" => "users#orders"
  get "/about_us" => "home#about_us"
  get "global_search" => "users#global_search"
  put "set_song_in_session" => "users#set_song_in_session"

    resources :tracks do
      member do
        get :download
        post :upload_tpt_file
        post :publish
        get :new_track_step2
        get :mp3_download
        get :download_zip
        get :download_wav
        get :download_tpt
        get :increment_play_count
      end
    
    collection do
      post :upload_trak_file
      get :upload_trak_file
      get :license
      get :new1
    end
    end
    resources :beatpacks 
  
  
  root 'users#index'  
  

end

app/models/glacier_detail.rb
class GlacierDetail < ActiveRecord::Base
  belongs_to :track
end

app/controllers/glacier_details_controller.rb
class GlacierDetailsController < ApplicationController
  before_action :set_glacier_detail, only: [:show, :edit, :update, :destroy]

  def index
    @glacier_details = GlacierDetail.all
  end

  def show
  end

  def new
    @glacier_detail = GlacierDetail.new
  end

  def edit
  end

  def create
    @glacier_detail = GlacierDetail.new(glacier_detail_params)

    respond_to do |format|
      if @glacier_detail.save
        format.html { redirect_to @glacier_detail, notice: 'Glacier detail was successfully created.' }
        format.json { render action: 'show', status: :created, location: @glacier_detail }
      else
        format.html { render action: 'new' }
        format.json { render json: @glacier_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @glacier_detail.update(glacier_detail_params)
        format.html { redirect_to @glacier_detail, notice: 'Glacier detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @glacier_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @glacier_detail.destroy
    respond_to do |format|
      format.html { redirect_to glacier_details_url }
      format.json { head :no_content }
    end
  end

  private
    def set_glacier_detail
      @glacier_detail = GlacierDetail.find(params[:id])
    end
    def glacier_detail_params
      params[:glacier_detail]
    end
end

app/helpers/glacier_details_helper.rb
module GlacierDetailsHelper
  
end

app/views/glacier_details/_form.html.erb
<%= form_for(@glacier_detail) do |f| %>
  <% if @glacier_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@glacier_detail.errors.count, "error") %> prohibited this glacier_detail from being saved:</h2>

      <ul>
      <% @glacier_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/glacier_details/edit.html.erb
<h1>Editing glacier_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @glacier_detail %> |
<%= link_to 'Back', glacier_details_path %>

app/views/glacier_details/index.html.erb
<h1>Listing glacier_details</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @glacier_details.each do |glacier_detail| %>
      <tr>
        <td><%= link_to 'Show', glacier_detail %></td>
        <td><%= link_to 'Edit', edit_glacier_detail_path(glacier_detail) %></td>
        <td><%= link_to 'Destroy', glacier_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Glacier detail', new_glacier_detail_path %>

app/views/glacier_details/new.html.erb
<h1>New glacier_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', glacier_details_path %>

app/views/glacier_details/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_glacier_detail_path(@glacier_detail) %> |
<%= link_to 'Back', glacier_details_path %>