config/routes.rb
Beatbucks::Application.routes.draw do
  
     
    resources :payment_notifications

    resources :line_items

  resources :carts do
    member do
      get :checkout
      get :billing
      post :save_billing
      get :download
    end
    collection do
      get :current
      get :billing_payments
      get :billing_payments2
      get :billing_payments3
      post :complete_payment
      get :payment_done
      get :license_agrement
      post :add_to_cart
      
      get :latest_pending_cart
      get :latest_pending_line_items
    end
    end

   resources :glacier_details

   devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", :registrations => "registrations" }
  as :user do
    get "settings" => "users#settings"
    get "social_networks" => "users#social_networks"
    put "users/:id/save_settings" => "users#save_settings"
    get "/profile" => "registrations#edit"
  end
  #map.current_cart 'cart', :controller => 'carts', :action => 'show', :id => 'current'
   get "/users/index"
   get "/registrations/update"
   post "/registrations/update"
   get "/home/state_cities"
   get "/home/state_codes"
   get "/dashbord" => "home#dashbord"
   get "/edit" => "users#edit"
   post "/tracks/download_zip" => "tracks#download_zip"
   post "/home/settings"
   get "/home/sub_genres"
   get "/beatpacks" => "beatpacks#new"
   get "/earnings" => "producers#earnings"

    get "/buy" => "users#buy"
    get "/license" => "users#license"
    get "/music" => "users#music"
    get "/files" => "users#files"
  get "/descripition" => "users#descripition"
  get "/author_profile/:id" => "users#author_profile"
  
  get "/orders" => "users#orders"
  get "/about_us" => "home#about_us"
  get "global_search" => "users#global_search"
  put "set_song_in_session" => "users#set_song_in_session"

    resources :tracks do
      member do
        get :download
        post :upload_tpt_file
        post :publish
        get :new_track_step2
        get :mp3_download
        get :download_zip
        get :download_wav
        get :download_tpt
        get :increment_play_count
      end
    
    collection do
      post :upload_trak_file
      get :upload_trak_file
      get :license
      get :new1
    end
    end
    resources :beatpacks 
  
  
  root 'users#index'  
  

end

app/models/beatpack.rb
class Beatpack < ActiveRecord::Base
	belongs_to :user
	attr_accessible :Title,:Trackscount,:Comment,:Downloadcount
	#validates :Title, length: { maximum:25 } presence: true

end

app/controllers/beatpacks_controller.rb
class BeatpacksController < ApplicationController
 
  before_action :set_beatpack, only: [:show, :edit, :update, :destroy ]
  layout "user_layout"
  
  def index
    redirect_to :controller => :beatpacks, :action => :new 
  end

  def show
	  @beatpack = Beatpack.find(params[:id])
  end

  def new
    @beatpack = Beatpack.new
  end

  def edit
  
  end

  def create
    @beatpack = Beatpack.new(beatpack_params)
    respond_to do |format|
      if @beatpack.save
        format.html { render action: 'publish', notice: 'Beatpack was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beatpack }
      else
        format.html { render action: 'new' }
        format.json { render json: @beatpack.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @beatpack, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beatpack.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @beatpack.destroy
    respond_to do |format|
      format.html { redirect_to beatpacks_url }
      format.json { head :no_content }
    end
  end

  private
    
    def set_beatpack
      @beatpack = Beatpack.find(params[:id])
    end

     
    def beatpack_params
      #params.require(:beatpack).permit(:Title , :Trackscount, :Comment, :Downloadcount, :user_id )
                                   
    end
 end


 

app/helpers/beatpacks_helper.rb
module BeatpacksHelper
end

app/views/beatpacks/_addnewtrack.html.erb
<!DOCTYPE HTML>
<html>
    <head>
        <title>ADDNEWTRACK</title>
    </head>
    <body>
        <header class="container"></header>

        <div class="container">
        	<div class="row-fluid dashboard">
                <div class="span9">
            		<div class="d_right">
                    	<div class="row-fluid top_h">
                            <div class="span12"> <h2><%= image_tag ("add_ico.png") %> Add New Track</h2></div>
                        </div>
                       <div class="row-fluid add_track">
                       		<div class="span3"></div>
                            <div class="span3 upload"><%= image_tag ("upload.png") %><h4>Select beat to upload <span>Select beat to upload</span></h4></div>
                            <div class="span1"></div>
                            <div class="span5">
                            	<ul class="create_cat">
                                	<li>WAV format only</li>
                                    <li>Disable all FX on master bus</li>
                                    <li>Make sure beat is free of sound tag</li>
                                    <li>Make sure beat is free of sound tag</li>
                                    <li>If you wanna upload your Track outs: Wait a bit, there will be a spot for that in a couple seconds</li>
                                </ul>
                            </div>
                        </div>
                   </div>
            	</div>
            </div>
        </div>

    </body>

</html>

app/views/beatpacks/_form.html.erb
<%= render :partial => 'layouts/user_sidebar' %>
<%= form_for Beatpack.new do |f| %>
  <% if @beatpack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beatpack.errors.count, "error") %> prohibited this track from being saved:</h2>
      <ul>
        <% @beatpack.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="span9">
  <div class="container">
    <div class="row-fluid dashboard">
      <div class="span9">
        <div class="d_right">
          <div class="row-fluid top_h">
                <div class="span9"> <h3><%= image_tag "2beat.png" %> <span>Beat Packs /</span> Create Beat Pack</h3></div>
                <div class="span3">
                  <a href="#" class="save">Save</a>
                    <a href="#" class="save">cancel</a>
                </div>
          </div>
          
          <div class="fm_sec">
            <h3>BASIC INFO</h3>
            <div class="row-fluid raw_sec">
              <div class="span2">Title</div>
              <div class="span10"><input type="text" /></div>
              </div>
              <div class="row-fluid raw_sec"><!--raw section!-->
                <div class="span6">
                  <div class="row-fluid raw_sec">
                    <div class="span4"> </div>
                    <div class="span8"> </div>
                  </div>
                  <div class="row-fluid raw_sec">
                    <div class="span4">Image</div>
                    <div class="span8"><input type="text" value="Browse featured image.." class="browse" /></div>
                  </div>
                </div>
                <div class="span6">
                  <div class="row-fluid raw_sec">
                    <div class="span4"> </div>
                    <div class="span8"> </div>
                  </div>
                  <div class="row-fluid raw_sec">
                    <div class="span4"> </div>
                    <div class="span8"> </div>
                  </div>
                </div>
              </div>
            </div>

            <h3>SELECT FEATURED TRACKS</h3>
            <div class="row-fluid s_track">
              <div class="span2"></div>
                <div class="span4">
                  <h3>Your tracks</h3>
                </div>
                <div class="span2 a_btn">
                  <a href="#" class="add">Add</a>
                  <a href="#" class="add">Remove</a>
                </div>
                <div class="span4">
                  <h3>Beat Pack track list</h3>
                    <ul>
                      <li>Themata</li>
                        <li>The Lone Ranger</li>
                        <li>Microfire</li>
                        <li>Lulalby of Birdland</li>
                        <li>Soliloquy</li>
                        <li>Quiet Night</li>
                      </ul>
                </div>
              </div>

              <div class="fm_sec no_bdr">
                <h3>LICENSE<span>(s)</span></h3>
                  <div class="row-fluid">
                    <div class="span6">
                        <div class="linces_sec">
                            <div class="row-fluid">
                                <div class="span1"><%= image_tag "checked.png" %></div>
                                  <div class="span11">
                                    <h3>Promotion only</h3>
                                      <p>Customer does not make money with the beat.*</p>
                                      <div class="row-fluid">
                                        <div class="span5">
                                          <label>License price</label>
                                          <input type="text" />
                                        </div>
                                        <div class="span2"></div>
                                        <div class="span5">
                                          <label>TPT Price</label>
                                          <input type="text" />
                                        </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          
                          <div class="linces_sec">
                              <div class="row-fluid">
                                  <div class="span1"><%= image_tag "checked.png" %></div>
                                  <div class="span11">
                                    <h3>For profit</h3>
                                      <p>Customer makes money with the beat.</p>
                                      <div class="row-fluid">
                                        <div class="span5">
                                          <label>License price</label>
                                          <input type="text" />
                                        </div>
                                        <div class="span2"></div>
                                        <div class="span5">
                                          <label>TPT Price</label>
                                          <input type="text" />
                                        </div>
                                      </div>
                                    </div>
                                </div>
                            </div>
                          </div>
                        
                        
                        <div class="span6">
                          <div class="linces_sec">
                            <div class="row-fluid">
                                <div class="span1"><%= image_tag "checked.png" %></div>
                                  <div class="span11">
                                    <h3>Exclusive</h3>
                                      <p>Customer has a lifetime exclusive right to make money from this beat.  Beat has never been sold before, nor will after***.</p>
                                      <div class="row-fluid"><!--row section!-->
                                        <div class="span5">
                                            <label>License price</label>
                                              <input type="text" />
                                          </div>
                                           <div class="span2"></div>
                                          <div class="span5">
                                            <label>TPT Price</label>
                                              <input type="text" />
                                          </div>
                                         
                                      </div><!--row section!-->
                                  </div>
                              </div>
                            </div><!--lincess section!-->
                            
                            <h6>* except from performance royalties due to statutory usage like when aired on the radio or on some non-interactive streaming services.</h6>
                            <h6><em>** The amount will be applied IN ADDITION to license price.</em></h6>
                            <h6><em>*** Therefore, if this license is bought, the beat will be remove.  In the event that any other license is sold, the Exclusive license selection will be removed and won't be available anymore for this beat (in order to respect the plrinciple of exclusivity; a beat is not exclusive if 2 different persons have the right to use it).</em></h6>
                          
                        </div>
                      </div>
                      <div class="span12 save_btn"> <%= f.submit "I'M DONE" %> </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>  
 
 

 





 


<% end %>
 

app/views/beatpacks/addnewtrack.html.erb
<%= render 'addnewtrack' %>

app/views/beatpacks/addnewtrack.js.erb
$(".span9").html("<%= escape_javascript(render("/beatpacks/addnewtrack")) %>");

app/views/beatpacks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/beatpacks/index.html.erb
<h1>Listing B</h1>
<table>
  <thead>
    <tr>
      <th>Mp3 File</th>
      <th>Track File</th>
      <th>TPT File</th>
      <th>TPT Files Count</th>
      <th>Title</th>
      <th>Bpm</th>
      <th>Genere</th>
      <th>Subgenere</th>
      <th>Tags</th>
      <th>Key</th>
      <th>Mood1</th>
      <th>Mood2</th>
      <th>Comment</th>
      <th>Promotion licence price</th>
      <th>Promotion tpt price</th>
      <th>Exclusive licence price</th>
      <th>Exclusive tpt price</th>
      <th>Profit licence price</th>
      <th>Profit tpt price</th>
      <th>User</th>
      <th>Download count</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @beatpacks.each do |track| %>
      <tr>
        <td>
          <% if track.mp3_track_file? %>
            <%= link_to 'Download', mp3_download_track_path(track) %>
          <% end %>
        </td>
        <td>
          <% if track.track_file? %>
            <%= link_to 'Download', download_track_path(track) %>
          <% end %>
        </td>
        <td>
          <% if track.tpt? %>
            <%= link_to 'Download', track.tpt.url %>
          <% end %>
        </td>
        <td><%= track.tpt_files_count %></td>
        <td><%= track.title %></td>
        <td><%= track.bpm %></td>
        <td><%= track.genere %></td>
        <td><%= track.subgenere %></td>
        <td><%= track.tags %></td>
        <td><%= track.key %></td>
        <td><%= track.mood1 %></td>
        <td><%= track.mood2 %></td>
        <td><%= track.comment %></td>
        <td><%= track.promotion_licence_price %></td>
        <td><%= track.promotion_tpt_price %></td>
        <td><%= track.exclusive_licence_price %></td>
        <td><%= track.exclusive_tpt_price %></td>
        <td><%= track.profit_licence_price %></td>
        <td><%= track.profit_tpt_price %></td>
        <td><%= track.user_id %></td>
        <td><%= track.download_count %></td>
        <td><%= track.active %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= image_tag ("plus.png") %>
<%= link_to 'ADD NEW TRACK', new_track_path %>

app/views/beatpacks/index.js.erb
$(".span9").html("<%= escape_javascript(render("/beatpacks/form")) %>");

   

app/views/beatpacks/new.html.erb
 

<%= render 'form' %>

<%= link_to 'Back to beatpacks', beatpacks_path %>

app/views/beatpacks/new.js.erb
$(".span9").html("<%= escape_javascript(render("/beatpacks/form")) %>");

 

app/views/beatpacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @beatpack.Title %>
</p>

 

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>