config/routes.rb
Beatbucks::Application.routes.draw do
  
     
    resources :payment_notifications

    resources :line_items

  resources :carts do
    member do
      get :checkout
      get :billing
      post :save_billing
      get :download
    end
    collection do
      get :current
      get :billing_payments
      get :billing_payments2
      get :billing_payments3
      post :complete_payment
      get :payment_done
      get :license_agrement
      post :add_to_cart
      
      get :latest_pending_cart
      get :latest_pending_line_items
    end
    end

   resources :glacier_details

   devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", :registrations => "registrations" }
  as :user do
    get "settings" => "users#settings"
    get "social_networks" => "users#social_networks"
    put "users/:id/save_settings" => "users#save_settings"
    get "/profile" => "registrations#edit"
  end
  #map.current_cart 'cart', :controller => 'carts', :action => 'show', :id => 'current'
   get "/users/index"
   get "/registrations/update"
   post "/registrations/update"
   get "/home/state_cities"
   get "/home/state_codes"
   get "/dashbord" => "home#dashbord"
   get "/edit" => "users#edit"
   post "/tracks/download_zip" => "tracks#download_zip"
   post "/home/settings"
   get "/home/sub_genres"
   get "/beatpacks" => "beatpacks#new"
   get "/earnings" => "producers#earnings"

    get "/buy" => "users#buy"
    get "/license" => "users#license"
    get "/music" => "users#music"
    get "/files" => "users#files"
  get "/descripition" => "users#descripition"
  get "/author_profile/:id" => "users#author_profile"
  
  get "/orders" => "users#orders"
  get "/about_us" => "home#about_us"
  get "global_search" => "users#global_search"
  put "set_song_in_session" => "users#set_song_in_session"

    resources :tracks do
      member do
        get :download
        post :upload_tpt_file
        post :publish
        get :new_track_step2
        get :mp3_download
        get :download_zip
        get :download_wav
        get :download_tpt
        get :increment_play_count
      end
    
    collection do
      post :upload_trak_file
      get :upload_trak_file
      get :license
      get :new1
    end
    end
    resources :beatpacks 
  
  
  root 'users#index'  
  

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :track
  attr_accessible  :unit_price, :quantity,:cart_id,:track_id,:item_type,:tpt_flag
  
  def full_price
    unit_price.to_i * quantity.to_i
  end
  
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController

 def create
    @product = Track.find(params[:product_id])
    unit_price = 0
    if params[:track_type] == "promotion"
    	unit_price = @product.promotion_licence_price
      if params[:promotion_tpt_flag]
        unit_price += @product.promotion_tpt_price
      end
    elsif params[:track_type] == "profit"
    	unit_price = @product.profit_licence_price
      if params[:profit_tpt_flag]
        unit_price += @product.profit_tpt_price
      end
   	elsif params[:track_type] == "exclusive"
   		unit_price = @product.exclusive_licence_price
      if params[:exclusive_tpt_flag]
        unit_price += @product.exclusive_tpt_price
      end
   	end
    
    @line_item = LineItem.create!(:cart_id => current_cart.id, :track_id => @product.id, :item_type => params[:track_type], :tpt_flag => params[:tpt_flag],:quantity => 1, :unit_price => unit_price)
    flash[:notice] = "Added #{@product.title} to cart."
    redirect_to current_carts_url
  end

  def destroy
  	@line_item = LineItem.find_by_id(params[:id])
  	@line_item.destroy
    respond_to do |format|
      format.html { redirect_to current_carts_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>